version: '3.4'
services:
  rabbitmq:
    image: rabbitmq:3.8
      
  worker:
    build: .
    image: &img worker 
    command: [celery, worker, --app=apiworker.app,--queues=default, --beat]
    environment: &env      
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc
    depends_on:
      - rabbitmq
      - mongodb
    volumes: &app
      - ./app:/app 
      
  mongodb:
    image: mongo
    restart: always
    container_name: 'mongodb'
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=Token_prices
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=passwd
      - MONGODB_DATA_DIR=/data/db
      - MONDODB_LOG_DIR=/dev/null
    volumes:
      - ./mongo_db/ini/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo_db/data/db:/data/db
    ports:
      - '27017-27019:27017-27019'
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=passwd
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb